-- Adapta bancos criados pelo antigo EnsureCreated para o primeiro baseline versionado.
-- Todo o script roda dentro de uma transação do DatabaseMigrator.

ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "MustChangePassword" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LastLoginAtUtc" timestamp with time zone NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "NormalizedUserName" character varying(80) NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "NormalizedEmail" character varying(254) NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "EmailConfirmed" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "SecurityStamp" text NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "ConcurrencyStamp" text NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PhoneNumber" text NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LockoutEnd" timestamp with time zone NULL;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LockoutEnabled" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "AccessFailedCount" integer NOT NULL DEFAULT 0;
ALTER TABLE "Users" ALTER COLUMN "PasswordHash" DROP NOT NULL;

UPDATE "Users"
SET "NormalizedUserName" = UPPER("Username"),
    "NormalizedEmail" = UPPER("Email"),
    "EmailConfirmed" = TRUE,
    "SecurityStamp" = COALESCE("SecurityStamp", md5(random()::text || clock_timestamp()::text || "Id"::text)),
    "ConcurrencyStamp" = COALESCE("ConcurrencyStamp", md5(random()::text || clock_timestamp()::text || "Id"::text)),
    "LockoutEnabled" = TRUE,
    "MustChangePassword" = TRUE;

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserPermissionOverrides" (
    "UserId" uuid NOT NULL,
    "Permission" character varying(100) NOT NULL,
    "IsGranted" boolean NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedByUserId" uuid NULL,
    CONSTRAINT "PK_UserPermissionOverrides" PRIMARY KEY ("UserId", "Permission"),
    CONSTRAINT "FK_UserPermissionOverrides_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AuditEvents" (
    "Id" uuid NOT NULL,
    "ActorUserId" uuid NULL,
    "ActorUsername" character varying(80) NOT NULL,
    "Action" character varying(120) NOT NULL,
    "ResourceType" character varying(100) NOT NULL,
    "ResourceId" character varying(120) NULL,
    "Outcome" character varying(30) NOT NULL,
    "IpAddress" character varying(64) NULL,
    "UserAgent" character varying(500) NULL,
    "DetailsJson" character varying(4000) NULL,
    "OccurredAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("Id")
);

INSERT INTO "Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Admin', 'ADMIN', md5(random()::text)),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Professional', 'PROFESSIONAL', md5(random()::text)),
    ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'Receptionist', 'RECEPTIONIST', md5(random()::text))
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "UserRoles" ("UserId", "RoleId")
SELECT "Id",
       CASE
           WHEN "Role" IN ('Professional', 'Esthetician') THEN 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'::uuid
           WHEN "Role" IN ('Receptionist', 'Secretary') THEN 'cccccccc-cccc-cccc-cccc-cccccccccccc'::uuid
           ELSE 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'::uuid
       END
FROM "Users"
ON CONFLICT DO NOTHING;

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "Roles" ("NormalizedName");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "Users" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "Users" ("NormalizedEmail");
CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AuditEvents_OccurredAtUtc" ON "AuditEvents" ("OccurredAtUtc");
CREATE INDEX IF NOT EXISTS "IX_AuditEvents_ActorUserId_OccurredAtUtc" ON "AuditEvents" ("ActorUserId", "OccurredAtUtc");
CREATE INDEX IF NOT EXISTS "IX_AuditEvents_ResourceType_ResourceId" ON "AuditEvents" ("ResourceType", "ResourceId");
CREATE INDEX IF NOT EXISTS "IX_Clients_Name" ON "Clients" ("Name");
CREATE INDEX IF NOT EXISTS "IX_Clients_Phone" ON "Clients" ("Phone");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Clients_Cpf" ON "Clients" ("Cpf") WHERE "Cpf" <> '' AND NOT "IsDeleted";
CREATE INDEX IF NOT EXISTS "IX_Appointments_ScheduledDateTime" ON "Appointments" ("ScheduledDateTime");
CREATE INDEX IF NOT EXISTS "IX_Appointments_ClientId_ScheduledDateTime" ON "Appointments" ("ClientId", "ScheduledDateTime");
CREATE INDEX IF NOT EXISTS "IX_Appointments_ProcedureTypeId" ON "Appointments" ("ProcedureTypeId");
CREATE INDEX IF NOT EXISTS "IX_Leads_Phone" ON "Leads" ("Phone");
CREATE INDEX IF NOT EXISTS "IX_Leads_Status_CreatedAt" ON "Leads" ("Status", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_ClientId_SessionDate" ON "MedicalRecords" ("ClientId", "SessionDate");
CREATE INDEX IF NOT EXISTS "IX_MedicalRecords_AppointmentId" ON "MedicalRecords" ("AppointmentId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProcedureTypes_Name" ON "ProcedureTypes" ("Name");
CREATE INDEX IF NOT EXISTS "IX_ClientDocuments_ClientId_UploadedAt" ON "ClientDocuments" ("ClientId", "UploadedAt");
CREATE INDEX IF NOT EXISTS "IX_ClientPhotos_ClientId_CreatedAt" ON "ClientPhotos" ("ClientId", "CreatedAt");

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Appointments_ProcedureTypes_ProcedureTypeId') THEN
        ALTER TABLE "Appointments" ADD CONSTRAINT "FK_Appointments_ProcedureTypes_ProcedureTypeId"
            FOREIGN KEY ("ProcedureTypeId") REFERENCES "ProcedureTypes" ("Id") ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MedicalRecords_Appointments_AppointmentId') THEN
        ALTER TABLE "MedicalRecords" ADD CONSTRAINT "FK_MedicalRecords_Appointments_AppointmentId"
            FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('{{INITIAL_MIGRATION}}', '8.0.29')
ON CONFLICT DO NOTHING;
